tst_psg: tst_psg.o psg.o effects.o
	cc68x -g tst_psg.o psg.o effects.o -o tst_psg

tst_psg.o: tst_psg.c psg.h
	cc68x -g -c tst_psg.c

psg.o: psg.c psg.h
	cc68x -g -c psg.c

effects.o: effects.c psg.h
	cc68x -g -c effects.c


clean:
	$(RM) *.o *.tos
