tst_rend: t_render.o render.o raster.o model.o layout.o bitmaps.o font.o events.o
	cc68x -g t_render.o render.o raster.o model.o layout.o bitmaps.o font.o events.o -o tst_rend

raster.o: raster.c raster.h
	cc68x -g -c raster.c

font.o: font.c font.h
	cc68x -g -c font.c

bitmaps.o: bitmaps.c bitmaps.h
	cc68x -g -c bitmaps.c

model.o: model.c model.h
	cc68x -g -c model.c

events.o: events.c events.h
	cc68x -g -c events.c

layout.o: layout.c layout.h
	cc68x -g -c layout.c

render.o: render.c render.h
	cc68x -g -c render.c

t_render.o: t_render.c render.h
	cc68x -g -c t_render.c

clean:
	$(RM) *.o *.tos
