#ifndef LAYOUT_H
#define LAYOUT_H

#define PIECE_SIZE 4
#define GRID_WIDTH 10
#define GRID_HEIGHT 20

const extern int I_PIECE_LAYOUT[PIECE_SIZE][PIECE_SIZE];
const extern int J_PIECE_LAYOUT[PIECE_SIZE][PIECE_SIZE];
const extern int L_PIECE_LAYOUT[PIECE_SIZE][PIECE_SIZE];
const extern int O_PIECE_LAYOUT[PIECE_SIZE][PIECE_SIZE];
const extern int S_PIECE_LAYOUT[PIECE_SIZE][PIECE_SIZE];
const extern int T_PIECE_LAYOUT[PIECE_SIZE][PIECE_SIZE];
const extern int Z_PIECE_LAYOUT[PIECE_SIZE][PIECE_SIZE];
extern int GRID_LAYOUT[GRID_HEIGHT][GRID_WIDTH];

#endif