t_model: t_model.o model.o print.o
	cc68x -g t_model.o model.o print.o -o t_model

t_model.o: t_model.c model.h
	cc68x -g -c t_model.c

model.o: model.c model.h
	cc68x -g -c model.c

print.o: print.c print.h
	cc68x -g -c print.c

clean:
	$(RM) *.o *.tos
