#ifndef BITMAPS_H
#define BITMAPS_H

#include "types.h"

extern const UINT16 clear_tile[16];
extern const UINT16 tile[16];
extern const UINT16 I_piece[61];
extern const UINT16 J_piece[92];
extern const UINT16 L_piece[92];
extern const UINT16 O_piece[62];
extern const UINT16 S_piece[93];
extern const UINT16 T_piece[93];
extern const UINT16 Z_piece[93];
extern const UINT16 playing_field[3030];

#endif